### ISSUE TITLE
Provide a link on how to install/have access to a Salesforce test instance

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-documentation#24]
in https://access.qa.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/#t2sf-prerequisites

**Comment by apupier** [comment]
A possible way is to use developer.salesforce.com
Another way is to use a trial account on salesforce.com

@zregvart is using developers.salesforce.com, seems the good place to point at in case the user doesn't have its own test instance.

**Comment by apupier** [comment]
in fact, salesforce.com is not working because the API usage is not possible https://developer.salesforce.com/forums/?id=906F0000000D9Y2IAK , might worth mentioning it in the documentation

**Comment by TovaCohen** [comment]
So does this updated text resolve this issue?

You need an account in a Salesforce installation that is used for development. This account must have Salesforce API access, which is available in a Salesforce Enterprise account or a Salesforce Developer account.

**Comment by apupier** [comment]
> So does this updated text resolve this issue?
> 
> You need an account in a Salesforce installation that is used for development. This account must have Salesforce API access, which is available in a Salesforce Enterprise account or a Salesforce Developer account.

yes, the text is great. Do you have link also to developer.salesforce.com on "Salesforce Developer account" text?

**Comment by TovaCohen** [comment]
The updated text is in place and I added a link. You can use the link in Aurelien's initial comment to see the update.
