### ISSUE TITLE
Fuse ignite tutorial not working for search field in datamapper

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-documentation#25]
due to https://github.com/syndesisio/syndesis-datamapper/issues/54 
the step mentioning the search is not working https://access.qa.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/#t2sf-add-data-mapping-step
would worth mentioning to expand user waiting the upstream bug to be fixed

**Comment by TovaCohen** [comment]
I corrected this. The link in Aurelien's initial comment displays the updated doc.
