### ISSUE TITLE
Twitter OAuth name must be unique

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-documentation#26]
https://github.com/syndesisio/syndesis-documentation/blob/master/docs/tutorials/topics/register_with_twitter.adoc#L21

In the following linked doument step 5./iii. we should mention that Twitter OAuth name is required to be unique and the example `fuse-ignite` is already taken. Probably better to omit the example completely?

// @TovaCohen

**Comment by TovaCohen** [comment]
@dsimansk how's this:

In the *Name* field, enter a name for your new app. This name
must be unique among all names of apps registered with Twitter.

**Comment by dsimansk** [comment]
It's great imho :)

**Comment by TovaCohen** [comment]
Great. Thanks David, and and thanks for catching that. Just in time too - Fintan is about to push the tutorial to the public site. 
You can see the update here:
https://access.qa.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial

**Comment by dsimansk** [comment]
All creadits go to @maschmid, I'm just a promt messenger here.

**Comment by TovaCohen** [comment]
Thanks Marek!  And just fyi, the doc is available now on the customer portal to anyone who has the link
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/
