### ISSUE TITLE
Fix TP2 Documentation

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis-documentation#27]
1.6.4. - 2: change _Click Data Mapping_ to _Click_ **Data Mapper**
2.4.3. - 2: change _Click Data Mapping_ to _Click_ **Data Mapper**

2.4.3. - 5 - iv: change _Just below that_ to _Just_ **above** _that_ 

@TovaCohen  can you please look at that? Thanks.

**Comment by TovaCohen** [comment]
Hi @mastepan , thanks for letting me know. These updates are in place in the source files for the tutorial. I don't know if we will republish the tutorial for TP2, but if we do, these updates will be there. 
Thanks!
